Ready for PR
dmitryVargin/middle.messenger.praktikum.yandex pull request #1
Opened 2021-07-06 18:57 UTC by dmitryVargin

2021-07-07 13:19 UTC, nickchamel requested changes
Привет! В целом все хорошо, дизайн приятный, молодец! Есть несколько комментариев по коду, особенно обрати внимание на то, чтобы все было написано в едином стиле и хорошо читалось/правилось. Работу пока возвращаю

2021-07-07 13:19 UTC, nickchamel commented on index.html
> +<script src="src/index.js"></script>
Старайся следить за отступами, неплохо бы добавить

2021-07-07 13:19 UTC, nickchamel commented on package.json
> +  },
по сути здесь все devDependencies. А handlebars у тебя вроде как не используется, можно убрать

2021-07-07 13:19 UTC, nickchamel commented on server.js
> +
лишние переводы строк можно удалить, лучше если весь проект будет написан в едином стиле

2021-07-07 13:19 UTC, nickchamel commented on src/components/arrowButton/index.js
> +export default arrowButton;
1. ты можешь просто написать
```
export default `
  <div class="arrow-button {{classes}}">
    <img src=${arrowImg} alt=""/>
  </div>
`;
```
к тому же обрати внимание на оформление (перенос строк) - так лучше читать и поддерживать код
2. Имена классов лучше не прокидывать сюда, они должны быть статичными, если есть необходимость  в каком-либо классе в зависимости от чего-то, то лучше прокидывать пропсу, например `type` и уже в зависимости от нее добавлять/изменять класс в самом шаблоне

2021-07-07 13:19 UTC, nickchamel commented on src/components/button/index.js
> +export default button;
То же самое по оформление здесь и дальше в таких же местах
Кстати где-то ты используешь одинарные кавычки, а где-то двойные, постарайся привести к одному виду!

2021-07-07 13:19 UTC, nickchamel commented on src/index.js
> +  };
нет нужны при каждом вызове appCreator создавать объект с роутами, его можно вынести за пределы функции константой.

2021-07-07 13:19 UTC, nickchamel commented on src/index.js
> +  };
мок данные тоже

2021-07-07 13:19 UTC, nickchamel commented on src/index.js
> +                </main>`;
отступы можно сделать читаемей

2021-07-07 13:19 UTC, nickchamel commented on src/index.js
> +  const navLinks = document.querySelectorAll('.nav-list .link');
селектор лучше написать не через имена классов а через атрибут `path` - так ты избавишься от лишней привязанности слоев приложения

2021-07-07 13:19 UTC, nickchamel commented on src/index.js
> +});
у тебя дублируется логика здесь и выше в onNavigate, ее можно вынести в отдельную функцию, а вообще нет необходимости каждый раз при onNavigate навешивать обработчики, там это лишнее

2021-07-07 13:19 UTC, nickchamel commented on src/pages/profile/profile.tmpl.js
> +const arrowBtn = Templator.compile(arrowButton, { classes: 'toLeft' });
как выше писал, лучше прокидывать не имена классов, а например в данном случае `{ toLeft: true }` а в шаблоне уже добавлять необходимый класс если toLeft === true.
Так ты избавляешься от лишней привязки слоев приложения

2021-07-07 13:19 UTC, nickchamel commented on utils/get.js
> +  if (result === undefined) return result;
старайся полностью писать условия, в чеклисте об этом написано
```
if () {
   ...
}
```

2021-07-07 13:19 UTC, nickchamel commented on utils/isEmpty.js
> +  }
здесь тоже

2021-07-07 13:19 UTC, nickchamel commented on utils/templator.js
> +        }
логи можно убрать,
обработчики тоже лучше убрать.
Далее будет компонентный подход, все обработчики будут внутри своих модулей, в window ничего такого быть не должно

2021-07-07 22:49 UTC, dmitryVargin commented on src/index.js
> +});
Там была необходимость навешивать обработчики, из-за того что #root перерисовывался полностью и обработчики слетали.
Изменил этот подход.

2021-07-08 12:44 UTC, nickchamel approved these changes
Привет. Работу принимаю, оставил тебе еще просто пару комментов для улучшения. Успехов в дальнейшем!

2021-07-08 12:44 UTC, nickchamel commented on src/components/button/index.js
> +export default `<button type='{{type}}' class='button'>{{text}}</button>`;
выше ты экспортишь функцию, а дальше строки. Лучше приведи к одному виду. По идее можно везде сделать функции потому что любой шаблон может однажды заиметь какие-нибудь пропсы, к тому же логика будет везде одинаковой

2021-07-08 12:44 UTC, nickchamel commented on src/index.js
> +window.addEventListener('load', () => {
кстати лучше использовать `document. addEventListener('DOMContentLoaded'`
Иначе если будет много картинок тяжелых, например, то может получится ситуация, когда картинки еще грузятся а пользователь кликает, но обработчик еще не навешан

2021-07-08 14:54 UTC, dmitryVargin commented on src/components/button/index.js
> +export default `<button type='{{type}}' class='button'>{{text}}</button>`;
Можно вопрос.
Я не целиком понимаю идею с функциями которые отдают строку шаблон.
Ее впоследствии обрабатывает шаблонизатор с контекстом, и если я добавляю пропсы, зачем мне тогда вообще шаблонизатор. 
Зачем мне использовать такую запись:
const tmpl = (someProps)=>{
  return `<button someProps="${someProps}" type='{{type}}' class='button'>{{text}}</button>`
}
Если я могу сразу использовать такую: 
const tmpl = ({someProps, type,text })=>{
  return `<button someProps="${someProps}" type='${type}' class='button'>${text}}</button>`
}

2021-07-08 15:12 UTC, nickchamel commented on src/components/button/index.js
> +export default `<button type='{{type}}' class='button'>{{text}}</button>`;
Ну да тебе это и не нужно, оставь строки просто и все.
Просто ты сделал что у тебя метод compile принимает строку и объект контекста, а потом сам же сделал экспорт функции и в profile.tmpl пишешь
`Templator.compile(arrowButton({ direction: 'toLeft' }));`
заместо
`Templator.compile(arrowButton, { direction: 'toLeft' });`
А так да вообщем-то тебе и не нужны функции тут!

2021-07-17 20:17 UTC, merged