Sprint 3
dmitryVargin/middle.messenger.praktikum.yandex pull request #3
Opened 2021-08-22 15:21 UTC by dmitryVargin

2021-08-23 15:17 UTC, bhoodream requested changes
Отличная работа, так держать! Есть некоторые замечания и недоработки...
Помимо комментариев по коду, я еще столкнулся со следующими проблемами:
- [x] установка зависимостей сопровождается неприятным сайд эффектом (из за запуска `prepublish`), который никак не ожидаешь... Не очень понимаю зачем это сделано в таком виде, потому что по итогу после установки зависимостей, получаешь скомпиленный код прямо в исходниках и 70+ гит изменений.
- [x] запросы на обновление данных пользователя уходят с некорректным `json`ом (в этом видимо виновата путанница с `JSON.stringify` и `deepEncodeHTML`).
- [ ] запросы по обновлению аватаров не работают из-за CORS политики
- [ ] ошибки по eslint ✖ 120 problems (13 errors, 107 warnings)
- [ ] ошибки по stylelint

2021-08-23 15:17 UTC, bhoodream commented on .prettierrc.js
> +import React from 'react';
Очень интересно как в конфигурационный файл для притира попали импорты `react` и `prop-types` :)

2021-08-23 15:17 UTC, bhoodream commented on src/api/AuthApi.ts
> +  static async signUp(data: string): Promise<XMLHttpRequest> {
Не очень понятно зачем использовать `async` если внутри функции не используется `await`...
Методы `HTTP` возвращают промисы, которые не нуждаются в `async` приставке у внешней функции

2021-08-23 15:17 UTC, bhoodream commented on src/components/Messages/index.ts
> +    document.querySelector('.empty-chat')?.classList.add('hidden');
после `return` выполнение любой функции в `js` прекращается, то есть эти строки кода никогда не исполнятся...

2021-08-23 15:17 UTC, bhoodream commented on src/controllers/ChatsController.ts
> +    if (offset) {
Тут наверно нужно проверять `limit`?

2021-08-23 15:17 UTC, bhoodream commented on src/controllers/ChatsController.ts
> +    if (offset) {
Тут наверно нужно проверять `title`?

2021-08-23 15:17 UTC, bhoodream commented on src/pages/login/index.ts
> +          // const target = event.target as HTMLInputElement;
закомментированный код лучше подчищать

2021-08-23 15:17 UTC, bhoodream commented on src/pages/messenger/index.ts
> +              if (Array.isArray(messages)) {
Здесь бы очень пригодился `Array.concat()`

2021-08-23 15:17 UTC, bhoodream commented on src/utils/functions/isEqual.ts
> +function isPlainObject(value: unknown): value is PlainObject {
`isPlainObject` вынесена в отдельную утилиту `src/utils/functions/isPlainObject.ts`

2021-08-23 15:17 UTC, bhoodream commented on src/utils/variables.ts
> +export const resourcesUrl = 'https://ya-praktikum.tech/api/v2/resources'
Такого рода данные обычно характеризуют как константы и хранят на уровне с утилитами, например `src/constants/urls.ts`

2021-08-24 19:31 UTC, dmitryVargin commented
Исправлено по замечаниям.
Малую часть не запушил сразу. Была действительно ошибка с deepEncodeHTML, XSS реализовывал в конце за 20 минут и не потестил после.
В процессе исправлений пришлось изучить несколько полезных вещей в Typescript, которые были действительно очень нужны.
Не удалось победить весь линтинг и типизацию в функциях вроде deepClone и get, но покрыл точно около 95% остального.

2021-08-25 03:32 UTC, bhoodream approved these changes
Спасибо за правки, все мои пожелания учтены, с меня АПРУВ!

2021-08-25 03:32 UTC, bhoodream commented on src/utils/functions/deepEncodeHTML.ts
> +function deepEncodeHTML(data: string | [] | Record<string, any>): string | [] | Record<string, any> {
В Typescript тип массив записывается иначе, у тебя щас некорректная запись https://www.typescriptlang.org/docs/handbook/basic-types.html#array

2021-08-25 03:32 UTC, bhoodream commented on src/utils/functions/deepEncodeHTML.ts
> +    if (typeof data === 'object') {
Ты же вроде бы уже проверил тут что это `isPlainObject`, по идее не надо проверять тип повторно

2021-08-25 03:32 UTC, bhoodream commented on src/utils/functions/deepEncodeHTML.ts
> +      for (const key in data) {
Этот цикл можно заменить на `Object.keys(data).forEach(...)`, не придется проверять `hasOwnProperty`, так как метод `keys()` обходит только личные свойства объекта

2021-08-28 19:08 UTC, merged